### ISSUE TITLE
Homework 2

### ISSUE THREAD

**Issue by OlimpiaZurek** [manav22/bigcorp-lotteries-api#3]
I checked your implementation of homework 2 and overall the code looks good. 
`Typescript`,  `Eslint` and `Babel `are configured and the types are implemented correctly.

I leave some suggestions:

- Delete the`build-tsc` folder - There is a standard that all build folders are added to the .`gitignore` file. This will prevent them from being added to your pushed files.
- The `vite-plugin-checker` package should be installed as a dev dependency
- Add `await client.connect()` to the `app.listen` function (see explanation from Wiktor's previous review)

**Comment by manav22** [comment]
Thank you for the feedback. Will update accordingly in the next homework.
